Transfer/urls.py
from django.urls import path, include
from . import views

app_name = "Transfer"

urlpatterns = [
    path('', views.homeview, name="Home"),
    path('logout', views.logout_view, name="Logout"),
    path('login', views.login_view, name="Login"),
    path('register', views.registerview, name="Register"),
    path('dashboard', views.dashboard, name="Dashboard"),
]

TransferApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Transfer.urls", namespace="transfer")),
]

Transfer/models.py
from django.db import models
# from django.contrib.auth.models import AbstractUser

# Create your models here.

class Client(models.Model):
    # valid_user = models.ForeignKey("Client", on_delete=models.CASCADE)
    first_name = models.CharField("First Name", max_length=35)
    last_name = models.CharField("Last Name", max_length=35)
    email = models.EmailField()
    username = models.CharField("Username", max_length=35)
    Acc_Num = models.CharField("Account Number", max_length=10)
    pin = models.CharField(max_length=4)

    def __str__(self):
        return self.first_name

# class Account(models.Model):
# )

Transfer/forms.py
from django import forms
from .models import Client


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client

        fields = [
            "first_name", "last_name", "email", "username", "pin"
        ]

        widget = {
            'pin': forms.PasswordInput(),
        }


# There is no need for this line of code 

# class LoginForm(forms.Form):
#     username = forms.CharField(max_length=20)
#     pin = forms.CharField(max_length=20, widget=forms.PasswordInput)

Transfer/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from .models import Client
from django.contrib.auth import get_user_model
from django.contrib.auth import login, logout, authenticate
from .forms import ClientForm
from django.contrib import messages
import random #Courtesy Jmoraks
import string #Courtesy Jmoraks
from django.conf import settings
from django.core.mail import send_mail



# Create your views here.

# User = get_user_model()

def homeview(request):
    return render(request, "landing_page.html", {})

def dashboard(request):
    return render(request, "dashboard.html", {})

def registerview(request):
    form = ClientForm()

    # This is the correct way of using forms in your views

    if request.method == "POST":
        form = ClientForm(request.POST)

        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_namae']
            email = form.cleaned_data['email']
            username = form.cleaned_data['username']
            pin = form.cleaned_data['pin']

            # Using cleaned_data is another way to get the correct inputs corresponding with the fields type in your MODELS.py

            Acc_Num = random.randint(100000000, 9999999999)

            if Client.objects.filter(username=username).exists():
                messages.info(request, "Username already exists")
                return redirect("transfer:Register")
            
            elif Client.objects.filter(email=email).exists():
                messages.info(request, "Email already exists")
                return redirect("transfer:Register")

            else:
                new_client = Client.objects.create(first_name=first_name, last_name=last_name, email=email, username=username, pin=pin, Acc_Num=Acc_Num)
                new_client.save()
                return redirect("transfer:Login")

        else:
            messages.info(request, 'Invalid details')
            return redirect('transfer:Register')

    else:
        return render(request, "Transfer/register.html", {"form": form})


def login_view(request):

    if request.method == "POST":
        username = request.POST['username']
        pin = request.POST['pin']

        user = authenticate(username=username, password=pin) # i changed this to password because pin is not a recognized variable name

        if user is not None:
            login(request, user)
            return redirect("transfer:Dashboard")

        else:
            messages.info(request, 'Invalid username/pin')
            return redirect('transfer:Login')

    else:
        return render(request, "Transfer/login.html")

def logout_view(request):
    logout(request)
    return redirect("/")

Transfer/templates/Transfer/login.html
{% extends 'base.html' %}

{% block content %}

<h1>LOGIN YOU❤!!!</h1> <br>

{% for message in messages %}
    <h4 style="color: red;">{{message}}</h4>
{% endfor %}


<form method="POST">
    {% csrf_token %}

    <p>
        <input type="text", name="username", placeholder="Username">
    </p>

    <p>
        <input type="password", name="pin", placeholder="Pin">
    </p>

    <br>
    <input type="submit" value="Submit">
</form>

{% endblock %}

Transfer/templates/Transfer/register.html
{% extends 'base.html' %}

{% block content %}

<h1>WELCOME YOU!!!</h1> <br>
{% for message in messages %}
    <h4 style="color: red;">{{message}}</h4>
{% endfor %}


<form method="POST">
    {% csrf_token %}
    {{form.as_p}} 
    <br>
    <input type="submit" value="Submit">
</form>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Transfer it</title>
</head>
<body>

{% include 'navbar.html' %}

{% block content %}
{% endblock %}

</body>
</html>

templates/dashboard.html
{%extends 'base.html' %}

{% block content %}

    {% if user.is_authenticated %}
        <h1>Welcome Back {{ user.username }} !</h1>
    {% endif %}
    


    
{%endblock%}

templates/landing_page.html
{% extends 'base.html' %}

{% block content %}

    {% if request.user.is_authenticated %}
        Welcome Back {{ request.user.username }}

    {% else %}
        This is the landing page. Proceed to SignUp 😊
        {% comment %} <a href="home.html">signup</a> {% endcomment %}

    {% endif %}

{% endblock %}

templates/navbar.html
{% if request.user.is_authenticated %}

<p> 
    <a href="#">Home</a>
    <a href="#">Settings</a>
    <a href="#">Transfer</a>
    <a href="#">Notification</a>
    <a href="{% url 'transfer:Logout' %}">Logout</a>

</p>

{% else %}

<p>
    <a href="{% url 'transfer:Login' %}">
        Login
    </a>
    <a href="{% url 'transfer:Register' %}">
        Signup
    </a>
</p>

{% endif %}









{% comment %} 

{% if request.user.is_authenticated %}

<p>
    <a style="text-decoration: none; color: black;", href="{% url 'register:logout' %}">
        <button>Logout</button>
    </a>
    <a style="text-decoration: none; color: black;", href="{% url 'trans:account' %}">
        <button>Home</button>
    </a>
    <a style="text-decoration: none; color: black", href="{% url 'trans:transfer-view' %}">
        <button>Transfer</button>
    </a>
    <a style="text-decoration: none; color: black", href="{% url 'trans:transfer-notify' %}">
        <button>Notification</button>
    </a>
</p>


{% else %}

<p>
    <a href="{% url 'register:login' %}">
        Login
    </a>
    <a href="{% url 'register:signup' %}">
        Signup
    </a>
</p>

{% endif %}

<hr> {% endcomment %}